version: '3'
services:

  proposta:
    image: 'andrey/proposta'
    ports:
      - 8081:8080
    depends_on:
      - "postgres"
    environment:
      DATABASE_URL: "jdbc:postgresql://postgres:5433/proposta"

  postgres:
    image: 'postgres:alpine'
    #volumes:
    #  - postgres-volume-app:/var/lib/postgresql/data
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: proposta
      POSTGRES_HOST: postgres

  mysql:
    image: 'mysql'
    #volumes:
    #  - mysql-volume-app:/var/lib/mysql/data
    ports:
      - 3307:3306
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: proposta
      POSTGRES_HOST: mysql

volumes:
  #postgres-volume-app:
  #mysql-volume-app: